version: "3.3"
services:
  static-site:
    container_name: static-site
    environment:
      - VIRTUAL_HOST=dercarsten.de
      - LETSENCRYPT_HOST=dercarsten.de
    volumes:
      - /etc/localtime:/etc/localtime:ro
    image: static-site
    ports:
      - "8080:80"
    restart: always
